package com.kp.marsh.ebt.server.webapp.data.domain;

// Generated Feb 1, 2011 12:09:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products implements java.io.Serializable {

	private int id;
	private Date created;
	private Integer optlock;
	private String itemType;
	private String itemName;
	private String parentId;
	private boolean enabled;
	private Set<BusinessInformation> businessInformations = new HashSet<BusinessInformation>(
			0);
	private String notes;
	private String eys_id;

	public Products() {
	}

	public Products(int id, Date created, String itemType, String itemName,
			boolean enabled) {
		this.id = id;
		this.created = created;
		this.itemType = itemType;
		this.itemName = itemName;
		this.enabled = enabled;
	}

	public Products(int id, Date created, Integer optlock, String itemType,
			String itemName, String parentId, boolean enabled,
			Set<BusinessInformation> businessInformations) {
		this.id = id;
		this.created = created;
		this.optlock = optlock;
		this.itemType = itemType;
		this.itemName = itemName;
		this.parentId = parentId;
		this.enabled = enabled;
		this.businessInformations = businessInformations;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Integer getOptlock() {
		return this.optlock;
	}

	public void setOptlock(Integer optlock) {
		this.optlock = optlock;
	}

	public String getItemType() {
		return this.itemType;
	}

	public void setItemType(String itemType) {
		this.itemType = itemType;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public Set<BusinessInformation> getBusinessInformations() {
		return this.businessInformations;
	}

	public void setBusinessInformations(
			Set<BusinessInformation> businessInformations) {
		this.businessInformations = businessInformations;
	}

	public String getNotes() {
		return notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public void setEys_id(String eys_id) {
		this.eys_id = eys_id;
	}

	public String getEys_id() {
		return eys_id;
	}

}
