package com.kp.marsh.ebt.server.webapp.data.domain;

// Generated Feb 1, 2011 12:09:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ReferenceYears generated by hbm2java
 */
public class ReferenceYears implements java.io.Serializable {

	private int id;
	private Date created;
	private Integer optlock;
	private Date editableFrom;
	private Date editableUntil;
	private int referenceYear;
	private Set<BusinessInformation> businessInformations = new HashSet<BusinessInformation>(
			0);

	public ReferenceYears() {
	}

	public ReferenceYears(int id, int referenceYear) {
		this.id = id;
		this.referenceYear = referenceYear;
	}

	public ReferenceYears(int id, Date created, Integer optlock,
			Date editableFrom, Date editableUntil, int referenceYear,
			Set<BusinessInformation> businessInformations) {
		this.id = id;
		this.created = created;
		this.optlock = optlock;
		this.editableFrom = editableFrom;
		this.editableUntil = editableUntil;
		this.referenceYear = referenceYear;
		this.businessInformations = businessInformations;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Integer getOptlock() {
		return this.optlock;
	}

	public void setOptlock(Integer optlock) {
		this.optlock = optlock;
	}

	public Date getEditableFrom() {
		return this.editableFrom;
	}

	public void setEditableFrom(Date editableFrom) {
		this.editableFrom = editableFrom;
	}

	public Date getEditableUntil() {
		return this.editableUntil;
	}

	public void setEditableUntil(Date editableUntil) {
		this.editableUntil = editableUntil;
	}

	public int getReferenceYear() {
		return this.referenceYear;
	}

	public void setReferenceYear(int referenceYear) {
		this.referenceYear = referenceYear;
	}

	public Set<BusinessInformation> getBusinessInformations() {
		return this.businessInformations;
	}

	public void setBusinessInformations(
			Set<BusinessInformation> businessInformations) {
		this.businessInformations = businessInformations;
	}

}
