//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.28 at 03:24:57 PM CEST 
//


package com.kp.malice.entities.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for BindingAuthorityDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BindingAuthorityDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BARefDate" type="{http://tempuri.org/ImportDataSet.xsd}Date"/>
 *         &lt;element name="BARefNo" type="{http://tempuri.org/ImportDataSet.xsd}BARefNo"/>
 *         &lt;element name="BABrokersRef" type="{http://tempuri.org/ImportDataSet.xsd}BABrokersRef"/>
 *         &lt;element name="BAPseudonym" type="{http://tempuri.org/ImportDataSet.xsd}BAPseudonym"/>
 *         &lt;element name="BANumber" type="{http://tempuri.org/ImportDataSet.xsd}BANumber"/>
 *         &lt;element name="BAcorr_Pin1" type="{http://tempuri.org/ImportDataSet.xsd}BAcorr_Pin1"/>
 *         &lt;element name="BAcorr_Pin2" type="{http://tempuri.org/ImportDataSet.xsd}BAcorr_Pin2"/>
 *         &lt;element name="Intermediary_Pin_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Intermediary_Pin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BindingAuthorityDetails", propOrder = {
    "baRefDate",
    "baRefNo",
    "baBrokersRef",
    "baPseudonym",
    "baNumber",
    "bAcorrPin1",
    "bAcorrPin2",
    "intermediaryPinType",
    "intermediaryPin"
})
public class BindingAuthorityDetails {

    @XmlElement(name = "BARefDate", required = true)
    protected XMLGregorianCalendar baRefDate;
    @XmlElement(name = "BARefNo")
    protected int baRefNo;
    @XmlElement(name = "BABrokersRef", required = true)
    protected String baBrokersRef;
    @XmlElement(name = "BAPseudonym", required = true)
    protected String baPseudonym;
    @XmlElement(name = "BANumber", required = true)
    protected String baNumber;
    @XmlElement(name = "BAcorr_Pin1")
    protected int bAcorrPin1;
    @XmlElement(name = "BAcorr_Pin2", required = true)
    protected String bAcorrPin2;
    @XmlElement(name = "Intermediary_Pin_type", required = true)
    protected String intermediaryPinType;
    @XmlElement(name = "Intermediary_Pin", required = true)
    protected String intermediaryPin;

    /**
     * Gets the value of the baRefDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBARefDate() {
        return baRefDate;
    }

    /**
     * Sets the value of the baRefDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBARefDate(XMLGregorianCalendar value) {
        this.baRefDate = value;
    }

    /**
     * Gets the value of the baRefNo property.
     * 
     */
    public int getBARefNo() {
        return baRefNo;
    }

    /**
     * Sets the value of the baRefNo property.
     * 
     */
    public void setBARefNo(int value) {
        this.baRefNo = value;
    }

    /**
     * Gets the value of the baBrokersRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBABrokersRef() {
        return baBrokersRef;
    }

    /**
     * Sets the value of the baBrokersRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBABrokersRef(String value) {
        this.baBrokersRef = value;
    }

    /**
     * Gets the value of the baPseudonym property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBAPseudonym() {
        return baPseudonym;
    }

    /**
     * Sets the value of the baPseudonym property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBAPseudonym(String value) {
        this.baPseudonym = value;
    }

    /**
     * Gets the value of the baNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBANumber() {
        return baNumber;
    }

    /**
     * Sets the value of the baNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBANumber(String value) {
        this.baNumber = value;
    }

    /**
     * Gets the value of the bAcorrPin1 property.
     * 
     */
    public int getBAcorrPin1() {
        return bAcorrPin1;
    }

    /**
     * Sets the value of the bAcorrPin1 property.
     * 
     */
    public void setBAcorrPin1(int value) {
        this.bAcorrPin1 = value;
    }

    /**
     * Gets the value of the bAcorrPin2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBAcorrPin2() {
        return bAcorrPin2;
    }

    /**
     * Sets the value of the bAcorrPin2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBAcorrPin2(String value) {
        this.bAcorrPin2 = value;
    }

    /**
     * Gets the value of the intermediaryPinType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntermediaryPinType() {
        return intermediaryPinType;
    }

    /**
     * Sets the value of the intermediaryPinType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntermediaryPinType(String value) {
        this.intermediaryPinType = value;
    }

    /**
     * Gets the value of the intermediaryPin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntermediaryPin() {
        return intermediaryPin;
    }

    /**
     * Sets the value of the intermediaryPin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntermediaryPin(String value) {
        this.intermediaryPin = value;
    }

}
