//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.28 at 03:24:57 PM CEST 
//


package com.kp.malice.entities.xml;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CertificateSecurityDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CertificateSecurityDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SecurityType" type="{http://tempuri.org/ImportDataSet.xsd}SecurityType"/>
 *         &lt;element name="LloydsPercentage" type="{http://tempuri.org/ImportDataSet.xsd}Percentage"/>
 *         &lt;element name="LloydsSecurityDetails" type="{http://tempuri.org/ImportDataSet.xsd}LloydsSecurityDetails" maxOccurs="16"/>
 *         &lt;element name="FollowerDetails" type="{http://tempuri.org/ImportDataSet.xsd}FollowerDetails" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CertificateSecurityDetails", propOrder = {
    "securityType",
    "lloydsPercentage",
    "lloydsSecurityDetails",
    "followerDetails"
})
public class CertificateSecurityDetails {

    @XmlElement(name = "SecurityType")
    protected int securityType;
    @XmlElement(name = "LloydsPercentage", required = true)
    protected BigDecimal lloydsPercentage;
    @XmlElement(name = "LloydsSecurityDetails", required = true)
    protected List<LloydsSecurityDetails> lloydsSecurityDetails;
    @XmlElement(name = "FollowerDetails")
    protected List<FollowerDetails> followerDetails;

    /**
     * Gets the value of the securityType property.
     * 
     */
    public int getSecurityType() {
        return securityType;
    }

    /**
     * Sets the value of the securityType property.
     * 
     */
    public void setSecurityType(int value) {
        this.securityType = value;
    }

    /**
     * Gets the value of the lloydsPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLloydsPercentage() {
        return lloydsPercentage;
    }

    /**
     * Sets the value of the lloydsPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLloydsPercentage(BigDecimal value) {
        this.lloydsPercentage = value;
    }

    /**
     * Gets the value of the lloydsSecurityDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lloydsSecurityDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLloydsSecurityDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LloydsSecurityDetails }
     * 
     * 
     */
    public List<LloydsSecurityDetails> getLloydsSecurityDetails() {
        if (lloydsSecurityDetails == null) {
            lloydsSecurityDetails = new ArrayList<LloydsSecurityDetails>();
        }
        return this.lloydsSecurityDetails;
    }

    /**
     * Gets the value of the followerDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the followerDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFollowerDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FollowerDetails }
     * 
     * 
     */
    public List<FollowerDetails> getFollowerDetails() {
        if (followerDetails == null) {
            followerDetails = new ArrayList<FollowerDetails>();
        }
        return this.followerDetails;
    }

}
