//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.28 at 03:24:57 PM CEST 
//


package com.kp.malice.entities.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CertificateDateTimeDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CertificateDateTimeDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InceptionDate" type="{http://tempuri.org/ImportDataSet.xsd}Date"/>
 *         &lt;element name="InceptionTime" type="{http://tempuri.org/ImportDataSet.xsd}Time"/>
 *         &lt;element name="ExpiryDate" type="{http://tempuri.org/ImportDataSet.xsd}Date"/>
 *         &lt;element name="ExpiryTime" type="{http://tempuri.org/ImportDataSet.xsd}Time"/>
 *         &lt;element name="ProposalDate" type="{http://tempuri.org/ImportDataSet.xsd}Date"/>
 *         &lt;element name="TacitRenewal" type="{http://tempuri.org/ImportDataSet.xsd}Boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CertificateDateTimeDetails", propOrder = {
    "inceptionDate",
    "inceptionTime",
    "expiryDate",
    "expiryTime",
    "proposalDate",
    "tacitRenewal"
})
public class CertificateDateTimeDetails {

    @XmlElement(name = "InceptionDate", required = true)
    protected XMLGregorianCalendar inceptionDate;
    @XmlElement(name = "InceptionTime", required = true)
    protected String inceptionTime;
    @XmlElement(name = "ExpiryDate", required = true)
    protected XMLGregorianCalendar expiryDate;
    @XmlElement(name = "ExpiryTime", required = true)
    protected String expiryTime;
    @XmlElement(name = "ProposalDate", required = true)
    protected XMLGregorianCalendar proposalDate;
    @XmlElement(name = "TacitRenewal")
    protected boolean tacitRenewal;

    /**
     * Gets the value of the inceptionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInceptionDate() {
        return inceptionDate;
    }

    /**
     * Sets the value of the inceptionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInceptionDate(XMLGregorianCalendar value) {
        this.inceptionDate = value;
    }

    /**
     * Gets the value of the inceptionTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInceptionTime() {
        return inceptionTime;
    }

    /**
     * Sets the value of the inceptionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInceptionTime(String value) {
        this.inceptionTime = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpiryDate(XMLGregorianCalendar value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the expiryTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpiryTime() {
        return expiryTime;
    }

    /**
     * Sets the value of the expiryTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpiryTime(String value) {
        this.expiryTime = value;
    }

    /**
     * Gets the value of the proposalDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getProposalDate() {
        return proposalDate;
    }

    /**
     * Sets the value of the proposalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProposalDate(XMLGregorianCalendar value) {
        this.proposalDate = value;
    }

    /**
     * Gets the value of the tacitRenewal property.
     * 
     */
    public boolean isTacitRenewal() {
        return tacitRenewal;
    }

    /**
     * Sets the value of the tacitRenewal property.
     * 
     */
    public void setTacitRenewal(boolean value) {
        this.tacitRenewal = value;
    }

}
