//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.28 at 03:24:57 PM CEST 
//


package com.kp.malice.entities.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CertificateConditions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CertificateConditions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PolicyDescription" type="{http://tempuri.org/ImportDataSet.xsd}Description"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="GeneralConditions" type="{http://tempuri.org/ImportDataSet.xsd}Condition" minOccurs="0"/>
 *             &lt;element name="SpecialConditions" type="{http://tempuri.org/ImportDataSet.xsd}SpecialCondition" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="RenewalConditions" type="{http://tempuri.org/ImportDataSet.xsd}Condition" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="AddendaConditions" type="{http://tempuri.org/ImportDataSet.xsd}LongCondition" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element name="PaymentPlanDescription" type="{http://tempuri.org/ImportDataSet.xsd}PlanDescriptionCondition" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CertificateConditions", propOrder = {
    "policyDescription",
    "generalConditions",
    "specialConditions",
    "renewalConditions",
    "addendaConditions",
    "paymentPlanDescription"
})
public class CertificateConditions {

    @XmlElement(name = "PolicyDescription", required = true)
    protected String policyDescription;
    @XmlElement(name = "GeneralConditions")
    protected String generalConditions;
    @XmlElement(name = "SpecialConditions")
    protected String specialConditions;
    @XmlElement(name = "RenewalConditions")
    protected String renewalConditions;
    @XmlElement(name = "AddendaConditions")
    protected String addendaConditions;
    @XmlElement(name = "PaymentPlanDescription")
    protected String paymentPlanDescription;

    /**
     * Gets the value of the policyDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyDescription() {
        return policyDescription;
    }

    /**
     * Sets the value of the policyDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyDescription(String value) {
        this.policyDescription = value;
    }

    /**
     * Gets the value of the generalConditions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeneralConditions() {
        return generalConditions;
    }

    /**
     * Sets the value of the generalConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeneralConditions(String value) {
        this.generalConditions = value;
    }

    /**
     * Gets the value of the specialConditions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialConditions() {
        return specialConditions;
    }

    /**
     * Sets the value of the specialConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialConditions(String value) {
        this.specialConditions = value;
    }

    /**
     * Gets the value of the renewalConditions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRenewalConditions() {
        return renewalConditions;
    }

    /**
     * Sets the value of the renewalConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRenewalConditions(String value) {
        this.renewalConditions = value;
    }

    /**
     * Gets the value of the addendaConditions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddendaConditions() {
        return addendaConditions;
    }

    /**
     * Sets the value of the addendaConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddendaConditions(String value) {
        this.addendaConditions = value;
    }

    /**
     * Gets the value of the paymentPlanDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentPlanDescription() {
        return paymentPlanDescription;
    }

    /**
     * Sets the value of the paymentPlanDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentPlanDescription(String value) {
        this.paymentPlanDescription = value;
    }

}
