//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.28 at 03:24:57 PM CEST 
//


package com.kp.malice.entities.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DocumentReferences complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DocumentReferences">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CertificateICNumber" type="{http://tempuri.org/ImportDataSet.xsd}ICNumber"/>
 *         &lt;element name="ICNumber" type="{http://tempuri.org/ImportDataSet.xsd}ICNumber"/>
 *         &lt;element name="ICStatus" type="{http://tempuri.org/ImportDataSet.xsd}ICStatus"/>
 *         &lt;element name="ICType" type="{http://tempuri.org/ImportDataSet.xsd}ICType"/>
 *         &lt;element name="CoverholderPrintableReference" type="{http://tempuri.org/ImportDataSet.xsd}CoverholderReference" minOccurs="0"/>
 *         &lt;element name="RenewedICNumber" type="{http://tempuri.org/ImportDataSet.xsd}ICNumber"/>
 *         &lt;element name="OriginalICNumber" type="{http://tempuri.org/ImportDataSet.xsd}ICNumber"/>
 *         &lt;element name="RelatedInceptionDate" type="{http://tempuri.org/ImportDataSet.xsd}Date"/>
 *         &lt;element name="RelatedInceptionTime" type="{http://tempuri.org/ImportDataSet.xsd}Time"/>
 *         &lt;element name="RelatedExpiryDate" type="{http://tempuri.org/ImportDataSet.xsd}Date"/>
 *         &lt;element name="RelatedExpiryTime" type="{http://tempuri.org/ImportDataSet.xsd}Time"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentReferences", propOrder = {
    "certificateICNumber",
    "icNumber",
    "icStatus",
    "icType",
    "coverholderPrintableReference",
    "renewedICNumber",
    "originalICNumber",
    "relatedInceptionDate",
    "relatedInceptionTime",
    "relatedExpiryDate",
    "relatedExpiryTime"
})
public class DocumentReferences {

    @XmlElement(name = "CertificateICNumber", required = true)
    protected String certificateICNumber;
    @XmlElement(name = "ICNumber", required = true)
    protected String icNumber;
    @XmlElement(name = "ICStatus")
    protected int icStatus;
    @XmlElement(name = "ICType", required = true)
    protected ICType icType;
    @XmlElement(name = "CoverholderPrintableReference")
    protected String coverholderPrintableReference;
    @XmlElement(name = "RenewedICNumber", required = true)
    protected String renewedICNumber;
    @XmlElement(name = "OriginalICNumber", required = true)
    protected String originalICNumber;
    @XmlElement(name = "RelatedInceptionDate", required = true)
    protected XMLGregorianCalendar relatedInceptionDate;
    @XmlElement(name = "RelatedInceptionTime", required = true)
    protected String relatedInceptionTime;
    @XmlElement(name = "RelatedExpiryDate", required = true)
    protected XMLGregorianCalendar relatedExpiryDate;
    @XmlElement(name = "RelatedExpiryTime", required = true)
    protected String relatedExpiryTime;

    /**
     * Gets the value of the certificateICNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificateICNumber() {
        return certificateICNumber;
    }

    /**
     * Sets the value of the certificateICNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificateICNumber(String value) {
        this.certificateICNumber = value;
    }

    /**
     * Gets the value of the icNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getICNumber() {
        return icNumber;
    }

    /**
     * Sets the value of the icNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setICNumber(String value) {
        this.icNumber = value;
    }

    /**
     * Gets the value of the icStatus property.
     * 
     */
    public int getICStatus() {
        return icStatus;
    }

    /**
     * Sets the value of the icStatus property.
     * 
     */
    public void setICStatus(int value) {
        this.icStatus = value;
    }

    /**
     * Gets the value of the icType property.
     * 
     * @return
     *     possible object is
     *     {@link ICType }
     *     
     */
    public ICType getICType() {
        return icType;
    }

    /**
     * Sets the value of the icType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ICType }
     *     
     */
    public void setICType(ICType value) {
        this.icType = value;
    }

    /**
     * Gets the value of the coverholderPrintableReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverholderPrintableReference() {
        return coverholderPrintableReference;
    }

    /**
     * Sets the value of the coverholderPrintableReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverholderPrintableReference(String value) {
        this.coverholderPrintableReference = value;
    }

    /**
     * Gets the value of the renewedICNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRenewedICNumber() {
        return renewedICNumber;
    }

    /**
     * Sets the value of the renewedICNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRenewedICNumber(String value) {
        this.renewedICNumber = value;
    }

    /**
     * Gets the value of the originalICNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalICNumber() {
        return originalICNumber;
    }

    /**
     * Sets the value of the originalICNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalICNumber(String value) {
        this.originalICNumber = value;
    }

    /**
     * Gets the value of the relatedInceptionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRelatedInceptionDate() {
        return relatedInceptionDate;
    }

    /**
     * Sets the value of the relatedInceptionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRelatedInceptionDate(XMLGregorianCalendar value) {
        this.relatedInceptionDate = value;
    }

    /**
     * Gets the value of the relatedInceptionTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedInceptionTime() {
        return relatedInceptionTime;
    }

    /**
     * Sets the value of the relatedInceptionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedInceptionTime(String value) {
        this.relatedInceptionTime = value;
    }

    /**
     * Gets the value of the relatedExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRelatedExpiryDate() {
        return relatedExpiryDate;
    }

    /**
     * Sets the value of the relatedExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRelatedExpiryDate(XMLGregorianCalendar value) {
        this.relatedExpiryDate = value;
    }

    /**
     * Gets the value of the relatedExpiryTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedExpiryTime() {
        return relatedExpiryTime;
    }

    /**
     * Sets the value of the relatedExpiryTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedExpiryTime(String value) {
        this.relatedExpiryTime = value;
    }

}
