//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.28 at 03:24:57 PM CEST 
//


package com.kp.malice.entities.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Document complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Document">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BindingAuthorityDetails" type="{http://tempuri.org/ImportDataSet.xsd}BindingAuthorityDetails"/>
 *         &lt;element name="DocumentReferences" type="{http://tempuri.org/ImportDataSet.xsd}DocumentReferences"/>
 *         &lt;element name="PolicyholderDetails" type="{http://tempuri.org/ImportDataSet.xsd}PolicyholderDetails"/>
 *         &lt;element name="CertificateSecurityDetails" type="{http://tempuri.org/ImportDataSet.xsd}CertificateSecurityDetails"/>
 *         &lt;element name="CertificateDateTimeDetails" type="{http://tempuri.org/ImportDataSet.xsd}CertificateDateTimeDetails"/>
 *         &lt;element name="RiskPremiumDetails" type="{http://tempuri.org/ImportDataSet.xsd}RiskPremiumDetails" maxOccurs="unbounded"/>
 *         &lt;element name="TotalPremiumDetails" type="{http://tempuri.org/ImportDataSet.xsd}TotalPremiumDetails"/>
 *         &lt;element name="Instalments" type="{http://tempuri.org/ImportDataSet.xsd}InstalmentDetails" maxOccurs="2" minOccurs="0"/>
 *         &lt;element name="CertificateConditions" type="{http://tempuri.org/ImportDataSet.xsd}CertificateConditions"/>
 *         &lt;element name="CertificateAttachments" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GenerationMode" type="{http://tempuri.org/ImportDataSet.xsd}GenerationMode" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="LastUpdatedDate" use="required" type="{http://tempuri.org/ImportDataSet.xsd}Date" />
 *       &lt;attribute name="ModuleType" use="required" type="{http://tempuri.org/ImportDataSet.xsd}ModuleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Document", propOrder = {
    "bindingAuthorityDetails",
    "documentReferences",
    "policyholderDetails",
    "certificateSecurityDetails",
    "certificateDateTimeDetails",
    "riskPremiumDetails",
    "totalPremiumDetails",
    "instalments",
    "certificateConditions",
    "certificateAttachments",
    "generationMode"
})
public class Document {

    @XmlElement(name = "BindingAuthorityDetails", required = true)
    protected BindingAuthorityDetails bindingAuthorityDetails;
    @XmlElement(name = "DocumentReferences", required = true)
    protected DocumentReferences documentReferences;
    @XmlElement(name = "PolicyholderDetails", required = true)
    protected PolicyholderDetails policyholderDetails;
    @XmlElement(name = "CertificateSecurityDetails", required = true)
    protected CertificateSecurityDetails certificateSecurityDetails;
    @XmlElement(name = "CertificateDateTimeDetails", required = true)
    protected CertificateDateTimeDetails certificateDateTimeDetails;
    @XmlElement(name = "RiskPremiumDetails", required = true)
    protected List<RiskPremiumDetails> riskPremiumDetails;
    @XmlElement(name = "TotalPremiumDetails", required = true)
    protected TotalPremiumDetails totalPremiumDetails;
    @XmlElement(name = "Instalments")
    protected List<InstalmentDetails> instalments;
    @XmlElement(name = "CertificateConditions", required = true)
    protected CertificateConditions certificateConditions;
    @XmlElement(name = "CertificateAttachments", required = true)
    protected String certificateAttachments;
    @XmlElement(name = "GenerationMode")
    protected GenerationMode generationMode;
    @XmlAttribute(name = "LastUpdatedDate", namespace = "http://tempuri.org/ImportDataSet.xsd", required = true)
    protected XMLGregorianCalendar lastUpdatedDate;
    @XmlAttribute(name = "ModuleType", namespace = "http://tempuri.org/ImportDataSet.xsd", required = true)
    protected ModuleType moduleType;

    /**
     * Gets the value of the bindingAuthorityDetails property.
     * 
     * @return
     *     possible object is
     *     {@link BindingAuthorityDetails }
     *     
     */
    public BindingAuthorityDetails getBindingAuthorityDetails() {
        return bindingAuthorityDetails;
    }

    /**
     * Sets the value of the bindingAuthorityDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link BindingAuthorityDetails }
     *     
     */
    public void setBindingAuthorityDetails(BindingAuthorityDetails value) {
        this.bindingAuthorityDetails = value;
    }

    /**
     * Gets the value of the documentReferences property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentReferences }
     *     
     */
    public DocumentReferences getDocumentReferences() {
        return documentReferences;
    }

    /**
     * Sets the value of the documentReferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentReferences }
     *     
     */
    public void setDocumentReferences(DocumentReferences value) {
        this.documentReferences = value;
    }

    /**
     * Gets the value of the policyholderDetails property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyholderDetails }
     *     
     */
    public PolicyholderDetails getPolicyholderDetails() {
        return policyholderDetails;
    }

    /**
     * Sets the value of the policyholderDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyholderDetails }
     *     
     */
    public void setPolicyholderDetails(PolicyholderDetails value) {
        this.policyholderDetails = value;
    }

    /**
     * Gets the value of the certificateSecurityDetails property.
     * 
     * @return
     *     possible object is
     *     {@link CertificateSecurityDetails }
     *     
     */
    public CertificateSecurityDetails getCertificateSecurityDetails() {
        return certificateSecurityDetails;
    }

    /**
     * Sets the value of the certificateSecurityDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link CertificateSecurityDetails }
     *     
     */
    public void setCertificateSecurityDetails(CertificateSecurityDetails value) {
        this.certificateSecurityDetails = value;
    }

    /**
     * Gets the value of the certificateDateTimeDetails property.
     * 
     * @return
     *     possible object is
     *     {@link CertificateDateTimeDetails }
     *     
     */
    public CertificateDateTimeDetails getCertificateDateTimeDetails() {
        return certificateDateTimeDetails;
    }

    /**
     * Sets the value of the certificateDateTimeDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link CertificateDateTimeDetails }
     *     
     */
    public void setCertificateDateTimeDetails(CertificateDateTimeDetails value) {
        this.certificateDateTimeDetails = value;
    }

    /**
     * Gets the value of the riskPremiumDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the riskPremiumDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRiskPremiumDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RiskPremiumDetails }
     * 
     * 
     */
    public List<RiskPremiumDetails> getRiskPremiumDetails() {
        if (riskPremiumDetails == null) {
            riskPremiumDetails = new ArrayList<RiskPremiumDetails>();
        }
        return this.riskPremiumDetails;
    }

    /**
     * Gets the value of the totalPremiumDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TotalPremiumDetails }
     *     
     */
    public TotalPremiumDetails getTotalPremiumDetails() {
        return totalPremiumDetails;
    }

    /**
     * Sets the value of the totalPremiumDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TotalPremiumDetails }
     *     
     */
    public void setTotalPremiumDetails(TotalPremiumDetails value) {
        this.totalPremiumDetails = value;
    }

    /**
     * Gets the value of the instalments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instalments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstalments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InstalmentDetails }
     * 
     * 
     */
    public List<InstalmentDetails> getInstalments() {
        if (instalments == null) {
            instalments = new ArrayList<InstalmentDetails>();
        }
        return this.instalments;
    }

    /**
     * Gets the value of the certificateConditions property.
     * 
     * @return
     *     possible object is
     *     {@link CertificateConditions }
     *     
     */
    public CertificateConditions getCertificateConditions() {
        return certificateConditions;
    }

    /**
     * Sets the value of the certificateConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link CertificateConditions }
     *     
     */
    public void setCertificateConditions(CertificateConditions value) {
        this.certificateConditions = value;
    }

    /**
     * Gets the value of the certificateAttachments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificateAttachments() {
        return certificateAttachments;
    }

    /**
     * Sets the value of the certificateAttachments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificateAttachments(String value) {
        this.certificateAttachments = value;
    }

    /**
     * Gets the value of the generationMode property.
     * 
     * @return
     *     possible object is
     *     {@link GenerationMode }
     *     
     */
    public GenerationMode getGenerationMode() {
        return generationMode;
    }

    /**
     * Sets the value of the generationMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenerationMode }
     *     
     */
    public void setGenerationMode(GenerationMode value) {
        this.generationMode = value;
    }

    /**
     * Gets the value of the lastUpdatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    /**
     * Sets the value of the lastUpdatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastUpdatedDate(XMLGregorianCalendar value) {
        this.lastUpdatedDate = value;
    }

    /**
     * Gets the value of the moduleType property.
     * 
     * @return
     *     possible object is
     *     {@link ModuleType }
     *     
     */
    public ModuleType getModuleType() {
        return moduleType;
    }

    /**
     * Sets the value of the moduleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModuleType }
     *     
     */
    public void setModuleType(ModuleType value) {
        this.moduleType = value;
    }

}
