//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.28 at 03:24:57 PM CEST 
//


package com.kp.malice.entities.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.kp.malice.entities.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.kp.malice.entities.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GenerationMode }
     * 
     */
    public GenerationMode createGenerationMode() {
        return new GenerationMode();
    }

    /**
     * Create an instance of {@link TotalPremiumDetails }
     * 
     */
    public TotalPremiumDetails createTotalPremiumDetails() {
        return new TotalPremiumDetails();
    }

    /**
     * Create an instance of {@link InstalmentDetails }
     * 
     */
    public InstalmentDetails createInstalmentDetails() {
        return new InstalmentDetails();
    }

    /**
     * Create an instance of {@link CertificateSecurityDetails }
     * 
     */
    public CertificateSecurityDetails createCertificateSecurityDetails() {
        return new CertificateSecurityDetails();
    }

    /**
     * Create an instance of {@link ICType }
     * 
     */
    public ICType createICType() {
        return new ICType();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link FollowerDetails }
     * 
     */
    public FollowerDetails createFollowerDetails() {
        return new FollowerDetails();
    }

    /**
     * Create an instance of {@link DocumentReferences }
     * 
     */
    public DocumentReferences createDocumentReferences() {
        return new DocumentReferences();
    }

    /**
     * Create an instance of {@link ImportDataSet }
     * 
     */
    public ImportDataSet createImportDataSet() {
        return new ImportDataSet();
    }

    /**
     * Create an instance of {@link PolicyholderDetails }
     * 
     */
    public PolicyholderDetails createPolicyholderDetails() {
        return new PolicyholderDetails();
    }

    /**
     * Create an instance of {@link RiskPremiumDetails }
     * 
     */
    public RiskPremiumDetails createRiskPremiumDetails() {
        return new RiskPremiumDetails();
    }

    /**
     * Create an instance of {@link CertificateConditions }
     * 
     */
    public CertificateConditions createCertificateConditions() {
        return new CertificateConditions();
    }

    /**
     * Create an instance of {@link BindingAuthorityDetails }
     * 
     */
    public BindingAuthorityDetails createBindingAuthorityDetails() {
        return new BindingAuthorityDetails();
    }

    /**
     * Create an instance of {@link LloydsSecurityDetails }
     * 
     */
    public LloydsSecurityDetails createLloydsSecurityDetails() {
        return new LloydsSecurityDetails();
    }

    /**
     * Create an instance of {@link CertificateDateTimeDetails }
     * 
     */
    public CertificateDateTimeDetails createCertificateDateTimeDetails() {
        return new CertificateDateTimeDetails();
    }

}
