//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.28 at 03:24:57 PM CEST 
//


package com.kp.malice.entities.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PolicyholderDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PolicyholderDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="NonItalianPolicyholderCode" type="{http://tempuri.org/ImportDataSet.xsd}Description"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="FiscalCode" type="{http://tempuri.org/ImportDataSet.xsd}FiscalCode"/>
 *             &lt;element name="VATNumber" type="{http://tempuri.org/ImportDataSet.xsd}VATNumber" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element name="GenderType" type="{http://tempuri.org/ImportDataSet.xsd}GenderType"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="CompanyName" type="{http://tempuri.org/ImportDataSet.xsd}CompanyName"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="LastName" type="{http://tempuri.org/ImportDataSet.xsd}Name"/>
 *             &lt;element name="FirstName" type="{http://tempuri.org/ImportDataSet.xsd}Name" minOccurs="0"/>
 *             &lt;element name="JobTitle" type="{http://tempuri.org/ImportDataSet.xsd}Name" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element name="AddressLine1" type="{http://tempuri.org/ImportDataSet.xsd}AddressLine"/>
 *         &lt;element name="AddressLine2" type="{http://tempuri.org/ImportDataSet.xsd}AddressLine" minOccurs="0"/>
 *         &lt;element name="City" type="{http://tempuri.org/ImportDataSet.xsd}AddressLine"/>
 *         &lt;element name="PostCode" type="{http://tempuri.org/ImportDataSet.xsd}AddressLine"/>
 *         &lt;element name="Region" type="{http://tempuri.org/ImportDataSet.xsd}AddressLine"/>
 *         &lt;element name="Country" type="{http://tempuri.org/ImportDataSet.xsd}AddressLine"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PolicyholderDetails", propOrder = {
    "nonItalianPolicyholderCode",
    "fiscalCode",
    "vatNumber",
    "genderType",
    "companyName",
    "lastName",
    "firstName",
    "jobTitle",
    "addressLine1",
    "addressLine2",
    "city",
    "postCode",
    "region",
    "country"
})
public class PolicyholderDetails {

    @XmlElement(name = "NonItalianPolicyholderCode")
    protected String nonItalianPolicyholderCode;
    @XmlElement(name = "FiscalCode")
    protected String fiscalCode;
    @XmlElement(name = "VATNumber")
    protected String vatNumber;
    @XmlElement(name = "GenderType", required = true)
    protected GenderType genderType;
    @XmlElement(name = "CompanyName")
    protected String companyName;
    @XmlElement(name = "LastName")
    protected String lastName;
    @XmlElement(name = "FirstName")
    protected String firstName;
    @XmlElement(name = "JobTitle")
    protected String jobTitle;
    @XmlElement(name = "AddressLine1", required = true)
    protected String addressLine1;
    @XmlElement(name = "AddressLine2")
    protected String addressLine2;
    @XmlElement(name = "City", required = true)
    protected String city;
    @XmlElement(name = "PostCode", required = true)
    protected String postCode;
    @XmlElement(name = "Region", required = true)
    protected String region;
    @XmlElement(name = "Country", required = true)
    protected String country;

    /**
     * Gets the value of the nonItalianPolicyholderCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNonItalianPolicyholderCode() {
        return nonItalianPolicyholderCode;
    }

    /**
     * Sets the value of the nonItalianPolicyholderCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNonItalianPolicyholderCode(String value) {
        this.nonItalianPolicyholderCode = value;
    }

    /**
     * Gets the value of the fiscalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiscalCode() {
        return fiscalCode;
    }

    /**
     * Sets the value of the fiscalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiscalCode(String value) {
        this.fiscalCode = value;
    }

    /**
     * Gets the value of the vatNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVATNumber() {
        return vatNumber;
    }

    /**
     * Sets the value of the vatNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVATNumber(String value) {
        this.vatNumber = value;
    }

    /**
     * Gets the value of the genderType property.
     * 
     * @return
     *     possible object is
     *     {@link GenderType }
     *     
     */
    public GenderType getGenderType() {
        return genderType;
    }

    /**
     * Sets the value of the genderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenderType }
     *     
     */
    public void setGenderType(GenderType value) {
        this.genderType = value;
    }

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the jobTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobTitle() {
        return jobTitle;
    }

    /**
     * Sets the value of the jobTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobTitle(String value) {
        this.jobTitle = value;
    }

    /**
     * Gets the value of the addressLine1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine1() {
        return addressLine1;
    }

    /**
     * Sets the value of the addressLine1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine1(String value) {
        this.addressLine1 = value;
    }

    /**
     * Gets the value of the addressLine2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine2() {
        return addressLine2;
    }

    /**
     * Sets the value of the addressLine2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine2(String value) {
        this.addressLine2 = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the postCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * Sets the value of the postCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostCode(String value) {
        this.postCode = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegion(String value) {
        this.region = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

}
