//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.28 at 03:24:57 PM CEST 
//


package com.kp.malice.entities.xml;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RiskPremiumDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RiskPremiumDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BusinessType" type="{http://tempuri.org/ImportDataSet.xsd}BusinessType"/>
 *         &lt;element name="RiskReference" type="{http://tempuri.org/ImportDataSet.xsd}RiskReference"/>
 *         &lt;element name="Premium" type="{http://tempuri.org/ImportDataSet.xsd}Money"/>
 *         &lt;element name="Accessori" type="{http://tempuri.org/ImportDataSet.xsd}Money"/>
 *         &lt;element name="Tax" type="{http://tempuri.org/ImportDataSet.xsd}Money"/>
 *         &lt;element name="Gross" type="{http://tempuri.org/ImportDataSet.xsd}Money"/>
 *         &lt;element name="Premium_Commission_Perc" type="{http://tempuri.org/ImportDataSet.xsd}Percentage"/>
 *         &lt;element name="Accessori_Commission_Perc" type="{http://tempuri.org/ImportDataSet.xsd}Percentage"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RiskPremiumDetails", propOrder = {
    "businessType",
    "riskReference",
    "premium",
    "accessori",
    "tax",
    "gross",
    "premiumCommissionPerc",
    "accessoriCommissionPerc"
})
public class RiskPremiumDetails {

    @XmlElement(name = "BusinessType")
    protected int businessType;
    @XmlElement(name = "RiskReference")
    protected float riskReference;
    @XmlElement(name = "Premium", required = true)
    protected BigDecimal premium;
    @XmlElement(name = "Accessori", required = true)
    protected BigDecimal accessori;
    @XmlElement(name = "Tax", required = true)
    protected BigDecimal tax;
    @XmlElement(name = "Gross", required = true)
    protected BigDecimal gross;
    @XmlElement(name = "Premium_Commission_Perc", required = true)
    protected BigDecimal premiumCommissionPerc;
    @XmlElement(name = "Accessori_Commission_Perc", required = true)
    protected BigDecimal accessoriCommissionPerc;

    /**
     * Gets the value of the businessType property.
     * 
     */
    public int getBusinessType() {
        return businessType;
    }

    /**
     * Sets the value of the businessType property.
     * 
     */
    public void setBusinessType(int value) {
        this.businessType = value;
    }

    /**
     * Gets the value of the riskReference property.
     * 
     */
    public float getRiskReference() {
        return riskReference;
    }

    /**
     * Sets the value of the riskReference property.
     * 
     */
    public void setRiskReference(float value) {
        this.riskReference = value;
    }

    /**
     * Gets the value of the premium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPremium() {
        return premium;
    }

    /**
     * Sets the value of the premium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPremium(BigDecimal value) {
        this.premium = value;
    }

    /**
     * Gets the value of the accessori property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAccessori() {
        return accessori;
    }

    /**
     * Sets the value of the accessori property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAccessori(BigDecimal value) {
        this.accessori = value;
    }

    /**
     * Gets the value of the tax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTax() {
        return tax;
    }

    /**
     * Sets the value of the tax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTax(BigDecimal value) {
        this.tax = value;
    }

    /**
     * Gets the value of the gross property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGross() {
        return gross;
    }

    /**
     * Sets the value of the gross property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGross(BigDecimal value) {
        this.gross = value;
    }

    /**
     * Gets the value of the premiumCommissionPerc property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPremiumCommissionPerc() {
        return premiumCommissionPerc;
    }

    /**
     * Sets the value of the premiumCommissionPerc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPremiumCommissionPerc(BigDecimal value) {
        this.premiumCommissionPerc = value;
    }

    /**
     * Gets the value of the accessoriCommissionPerc property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAccessoriCommissionPerc() {
        return accessoriCommissionPerc;
    }

    /**
     * Sets the value of the accessoriCommissionPerc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAccessoriCommissionPerc(BigDecimal value) {
        this.accessoriCommissionPerc = value;
    }

}
